#!/bin/sh

python visualize_attention_upper.py --patch_size 16 --arch albef_large --pretrained_weights ~/ALBEF/output/pretrain/ALBEF_14M.pth --block_num 7 --output_dir ~/ALBEF/output/pretrain/ALBEF_14M/upper/layer_8/bus --image_path image/bus_641.jpg --sentence bus
python visualize_attention_upper.py --patch_size 16 --arch albef_large --pretrained_weights ~/ALBEF/output/pretrain/ALBEF_14M.pth --block_num 7 --output_dir ~/ALBEF/output/pretrain/ALBEF_14M/upper/layer_8/dog --image_path image/dog.jpg --sentence dog 
python visualize_attention_upper.py --patch_size 16 --arch albef_large --pretrained_weights ~/ALBEF/output/pretrain/ALBEF_14M.pth --block_num 7 --output_dir ~/ALBEF/output/pretrain/ALBEF_14M/upper/layer_8/baby --image_path image/baby_428.jpg --sentence baby
python visualize_attention_upper.py --patch_size 16 --arch albef_large --pretrained_weights ~/ALBEF/output/pretrain/ALBEF_14M.pth --block_num 7 --output_dir ~/ALBEF/output/pretrain/ALBEF_14M/upper/layer_8/giraffe --image_path image/giraffe_136.jpg --sentence giraffe
python visualize_attention_upper.py --patch_size 16 --arch albef_large --pretrained_weights ~/ALBEF/output/pretrain/ALBEF_14M.pth --block_num 7 --output_dir ~/ALBEF/output/pretrain/ALBEF_14M/upper/layer_8/old --image_path image/old_395.jpg --sentence old
python visualize_attention_upper.py --patch_size 16 --arch albef_large --pretrained_weights ~/ALBEF/output/pretrain/ALBEF_14M.pth --block_num 7 --output_dir ~/ALBEF/output/pretrain/ALBEF_14M/upper/layer_8/road --image_path image/road_257.jpg --sentence road
python visualize_attention_upper.py --patch_size 16 --arch albef_large --pretrained_weights ~/ALBEF/output/pretrain/ALBEF_14M.pth --block_num 7 --output_dir ~/ALBEF/output/pretrain/ALBEF_14M/upper/layer_8/baseball --image_path image/baseball544.jpg --sentence baseball
python visualize_attention_upper.py --patch_size 16 --arch albef_large --pretrained_weights ~/ALBEF/output/pretrain/ALBEF_14M.pth --block_num 7 --output_dir ~/ALBEF/output/pretrain/ALBEF_14M/upper/layer_8/game --image_path image/game_1626.jpg --sentence game
python visualize_attention_upper.py --patch_size 16 --arch albef_large --pretrained_weights ~/ALBEF/output/pretrain/ALBEF_14M.pth --block_num 7 --output_dir ~/ALBEF/output/pretrain/ALBEF_14M/upper/layer_8/room --image_path image/room.jpg --sentence room
python visualize_attention_upper.py --patch_size 16 --arch albef_large --pretrained_weights ~/ALBEF/output/pretrain/ALBEF_14M.pth --block_num 7 --output_dir ~/ALBEF/output/pretrain/ALBEF_14M/upper/layer_8/boat --image_path image/boat_400.jpg --sentence boat
